### ISSUE TITLE
Error after receiving a (268) QOS REPORT

### ISSUE THREAD

**Issue by hansgoos** [sipcapture/hepfix.js#2]
Hi,

I see the following error message after receiving a (268) QOS REPORT from our ACME/ORACLE SBC

> 268: QOS REPORT
{ CallID: '7DC57216AA112655@10.254.1.110' }
{ type: 'HEP',
  version: 3,
  payload_type: 'JSON',
  captureId: 2017,
  capturePass: 'oracme',
  ip_family: 2,
  protocol: 17,
  proto_type: 35,
  srcIp: undefined,
  dstIp: undefined,
  srcPort: undefined,
  dstPort: undefined,
  correlation_id: '7DC57216AA112655@10.254.1.110',
  mos: 440,
  time_sec: 1567681411,
  time_usec: 940 }
Sending HEP3 Packet to localhost:9060...
HEP3 Error sending!
TypeError: Cannot read property 'split' of undefined
    at Object.encapsulate (/var/opt/hepfix.js/node_modules/hep-js/index.js:89:23)
    at sendHEP3 (/var/opt/hepfix.js/hep-client.js:121:31)
    at Object.preHep (/var/opt/hepfix.js/hep-client.js:88:5)
    at MOSit (/var/opt/hepfix.js/hepfix.js:47:13)
    at fixHandler (/var/opt/hepfix.js/hepfix.js:212:5)
    at fixHandler (/var/opt/hepfix.js/hepfix.js:112:4)
    at Socket.<anonymous> (/var/opt/hepfix.js/hepfix.js:243:2)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)

The rest of the SIP messages are handled correctly, without errors.

**Comment by lmangani** [comment]
This is due to the `srcIp` being undefined:
```
	var d = rcinfo.srcIp.split('.');
```
We can and should fix this both here and in hep-js to deal with null values.
Are there any other log lines preceding this error in console?

**Comment by lmangani** [comment]
I pushed an updated version of `hep-js` which should handle this case - please update your hepfix to use hep-js 1.0.19 and let me know - mind HOMER won't know what to do with this type of report unless configured to do so.

**Comment by hansgoos** [comment]
After using hep-js 1.0.19 the error is gone. 
Thanks for your quick help!
